#pragma once

#if CONFIG_TESLASYNTH_DISPLAY_RESOLUTION_320x240

#define DISPLAY_WIDTH  320
#define DISPLAY_HEIGHT 240

#endif

#if CONFIG_TESLASYNTH_DISPLAY_BACKLIGHT_ACTIVE_HIGH
#define LCD_BK_LIGHT_ON_LEVEL 1
#elif CONFIG_TESLASYNTH_DISPLAY_BACKLIGHT_ACTIVE_LOW
#define LCD_BK_LIGHT_ON_LEVEL 0
#endif
#define LCD_BK_LIGHT_OFF_LEVEL !LCD_BK_LIGHT_ON_LEVEL
